# fly.toml app configuration file generated for github-raven-v2 on 2023-07-12T09:54:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "github-raven-v2"
primary_region = "den"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
